version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: macknighter/learning:pyhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: